### ISSUE TITLE
Twitter fails

### ISSUE THREAD

**Issue by frankV** [nraboy/ng-cordova-oauth-example#1]
using Twitter oauth fails without error. inAppBrowser is not even opened.

**Comment by nraboy** [comment]
A few questions here:
1. Are you trying to use Ionic Serve, Ionic View, or Ionic Live-Reload?
2. Are you using Android or iOS?
3. Are you testing on a device or simulator?
4. How are you tracking your logs?

Best,

**Comment by frankV** [comment]
> Are you trying to use Ionic Serve, Ionic View, or Ionic Live-Reload?

running in an emulator with live-reload

> Are you using Android or iOS?

iOS

> Are you testing on a device or simulator?

yes, currently simulator

> How are you tracking your logs?

using a combination of the `ionic run` console and I also `tail -f` the `platform/cordova` logs

This does work for Imgur in the example.

**Comment by nraboy** [comment]
Try to build the application with `ionic build ios` then manually open the Xcode project generated in **platforms/ios**.  When you run from the simulator, inspect the logs in Xcode.  Building and installing worked fine for me.  I'm running the latest version of everything.

I know no one likes to hear this, but I don't recommend live-reload.  It has given me a history of headaches.

Let me know what happens.

**Comment by frankV** [comment]
Solved. Guess I won't be using live-reload any longer. 
Do you believe me that this did work last week? Very strange that twitter is the only one I've tested so far that does this. Could it be the Oauth1 pains?

**Comment by nraboy** [comment]
So by ditching live-reload all is good now?

I believe you that it worked last week.  I'm not sure what exactly live-reload does at a low level, but for whatever reason the behavior is inconsistent.  Same inconsistencies exist with Ionic View and Ionic Serve.

I doubt Twitter is at fault here.

Reach out on Twitter if you need anything in the future :-)

**Comment by frankV** [comment]
Thanks again, Nic!

**Comment by dndeus** [comment]
Hi i'm having the same issue here with twitter service. What livereload have to do when i use a simulator??  

Anyway what i have to do, I didn't quite  understand what frank did

Thank you

**Comment by nraboy** [comment]
@dianikol I say this over and over again in the comments (and even include it in the ng-cordova-oauth documentation) that you cannot use live-reload, ionic view, ionic serve, or phonegap build with this library.

Regards,

**Comment by dndeus** [comment]
Thank you for answer Nic. I didn't use ant of these. I tried to use it on a device. With other services like Facebook i hadn't any issue. Just with the Twitter one :)
